# Generated by Django 5.2.1 on 2025-06-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=64)),
                ('planeModel', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(related_name='carriers', to='flights.flight')),
            ],
        ),
    ]
